name: YQTB

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: '10 12 * * *'
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          
      - name: 'Install requirements'
        run: |
          pip install -r ./requirements.txt
      - name: Run script
        env:
          config: ${{ secrets.config }}
        run: |
          python3 main.py
